name: Deploy to Environments

on:
  push:
    tags:
      - 'tag-v*' 

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up AWS CLI
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy to DEV
        run: |
          echo "Deploying to DEV environment using tag ${{ github.ref }}"

  deploy_to_qa:
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to QA
        run: |
          echo "Deploying to QA environment using tag ${{ github.ref }}"

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: deploy_to_qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PROD
        run: |
          echo "Deploying to PROD environment using tag ${{ github.ref }}"
