name: Deploy to Environments

on:
  push:
    tags:
      - '*'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DEV
        run: |
          echo "Deploying to DEV environment using tag ${{ github.ref }}"

  deploy_to_qa:
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to QA
        run: |
          echo "Deploying to QA environment using tag ${{ github.ref }}"

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: deploy_to_qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to PROD
        run: |
          echo "Deploying to PROD environment using tag ${{ github.ref }}"
