
name: Deploy from Tag

on:
  push:
    tags:
      - 'tag-v*.*.*'  # Trigger deployment for any versioned tags (e.g., v1.0.0)

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Dev environment
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"  # Extract tag from the GITHUB_REF variable
          echo "Deploying to Dev with tag: $TAG_VERSION"
          # Deploy to Dev using the tag version (AWS, GCP, etc.)

  deploy_to_qa:
    needs: deploy_to_dev
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to QA environment
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          echo "Deploying to QA with tag: $TAG_VERSION"
          # Deploy to QA using the tag version

      - name: Request QA Approval
        if: success()
        uses: peter-evans/approve-pull-request-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy_to_prod:
    needs: deploy_to_qa
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Prod environment
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          echo "Deploying to Prod with tag: $TAG_VERSION"
          # Deploy to Prod using the tag version

      - name: Request Prod Approval
        if: success()
        uses: peter-evans/approve-pull-request-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
