name: Tag Creation and Deployment Workflow

on:
  pull_request:
    branches:
      - main  # Only for PRs targeting the main branch
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    tags:
      - 'tag-v*'  # Trigger deployment on tag creation

jobs:
  # Job 1: Create Tag
  create_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Only run after PR merge
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git for tagging
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch tags from remote
        run: |
          # Fetch all tags from the remote
          git fetch --tags

      - name: Get latest tag
        id: get_latest_tag
        run: |
          # List all tags and find the most recent one
          LATEST_TAG=$(git tag --list 'tag-v*' | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="tag-v0.0.0"
          fi
          echo "Latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Parse version components
        id: parse_version
        run: |
          VERSION="${{ env.latest_tag }}"
          VERSION_PARTS=(${VERSION//./ })
          MAJOR="${VERSION_PARTS[0]//tag-v/}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"
          echo "MAJOR=$MAJOR"
          echo "MINOR=$MINOR"
          echo "PATCH=$PATCH"
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV
          echo "PATCH=$PATCH" >> $GITHUB_ENV

      - name: Increment version based on commit message
        id: increment_version
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MESSAGE" == *MAJOR* ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ "$COMMIT_MESSAGE" == *MINOR* ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [[ "$COMMIT_MESSAGE" == *PATCH* ]]; then
            PATCH=$((PATCH + 1))
          fi
          NEW_TAG="tag-v${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Check if the tag already exists
        id: check_tag
        run: |
          NEW_TAG="${{ env.NEW_TAG }}"
          # Check if the tag already exists in the remote repository
          TAG_EXISTS=$(git tag -l | grep "$NEW_TAG" || echo "")
          if [[ -n "$TAG_EXISTS" ]]; then
            echo "Tag $NEW_TAG already exists. Incrementing PATCH version."
            PATCH=$((PATCH + 1))
            NEW_TAG="tag-v${MAJOR}.${MINOR}.${PATCH}"
            echo "Updated to new tag: $NEW_TAG"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create and push the new tag
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          NEW_TAG="${{ env.NEW_TAG }}"
          git tag $NEW_TAG
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin $NEW_TAG
          echo "Created and pushed tag: $NEW_TAG"

  # Job 2: Deploy to DEV, QA, and PROD (triggered by tag push)
  deploy_to_environments:
    runs-on: ubuntu-latest
    needs: create_tag  # Only run after the tag is created
    if: github.event.ref == 'refs/tags/tag-v*'  # Only run when a tag is pushed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DEV
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Deploying to DEV environment using tag $TAG_NAME"
          # Add actual deployment command here

      - name: Deploy to QA
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Deploying to QA environment using tag $TAG_NAME"
          # Add actual deployment command here

      - name: Deploy to PROD
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Deploying to PROD environment using tag $TAG_NAME"
          # Add actual deployment command here
